(define (f)
   (print 5)
   (let loop ((i 0))
      (if (> i 3)
	  (loop (+ i 1))
	  (print "xyz")))
   (let ((x 5))
      (define (g)
	 (print "xxx")
	 (if (eq? 'x 'y)
	     (g)))
      (g)))
(f)

(define (h)
   (define (h1)
      (print "y"))
   (define (h2)
      (print "2"))
   (define (h3)
      (print "3")
      (set! h3 (lambda () (print "changed"))))
   (let loop ((i 0))
      (if (> i 3)
	  (loop (+ i 1))
	  (print "xyz")))
   (if #t
       (h1)
       (h2))
   (h3))
(h)

(js gg)
(set! gg (lambda () (print "external")))
